-- Organizations, users, memberships and API keys (plan/04 §9). IDs are UUIDv7 generated by the
-- application (10-engineering-standards.md §3); the database never generates them.

-- +goose Up
set local lock_timeout = '5s';
set local role dbcloud_migrator;

create table dbcloud.organizations (
  id            uuid primary key,
  name          text not null check (length(name) between 1 and 100),
  slug          text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
  billing_state text not null default 'active' check (billing_state in ('active', 'past_due', 'suspended', 'closed')),
  gstin         text check (gstin ~ '^[0-9]{2}[A-Z0-9]{10}[0-9][A-Z][0-9A-Z]$'),
  created_at    timestamptz not null default now()
);
comment on table dbcloud.organizations is 'Customer organizations; the tenancy boundary of the control plane. Owner: control-api.';
comment on column dbcloud.organizations.billing_state is 'active | past_due | suspended | closed; set by billing jobs from Razorpay state.';
comment on column dbcloud.organizations.gstin is 'Optional GST identification number of the customer, printed on invoices.';

create table dbcloud.users (
  id           uuid primary key,
  auth_user_id uuid not null unique,
  email        text not null check (length(email) between 3 and 320),
  created_at   timestamptz not null default now()
);
comment on table dbcloud.users is 'Dashboard users, one row per Supabase Auth user. Owner: control-api.';
comment on column dbcloud.users.auth_user_id is 'Supabase Auth user id (auth.users.id, the JWT sub). No foreign key: auth is owned by Supabase.';

create table dbcloud.memberships (
  org_id     uuid not null references dbcloud.organizations (id),
  user_id    uuid not null references dbcloud.users (id),
  role       text not null check (role in ('owner', 'admin', 'developer', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (org_id, user_id)
);
create index memberships_user_id_idx on dbcloud.memberships (user_id);
comment on table dbcloud.memberships is 'Which user belongs to which organization, with which role. Owner: control-api.';

create table dbcloud.api_keys (
  id           uuid primary key,
  org_id       uuid not null references dbcloud.organizations (id),
  name         text not null check (length(name) between 1 and 100),
  prefix       text not null unique check (prefix ~ '^dbc_[a-z2-7]{12}$'),
  hash         text not null check (hash like '$argon2id$%'),
  scopes       text[] not null default '{}',
  created_by   uuid references dbcloud.users (id),
  created_at   timestamptz not null default now(),
  expires_at   timestamptz,
  revoked_at   timestamptz,
  last_used_at timestamptz
);
create index api_keys_org_id_idx on dbcloud.api_keys (org_id, created_at desc, id);
comment on table dbcloud.api_keys is 'Organization API keys. Only the argon2id hash is stored (15-security §3); prefix is the public lookup part. Owner: control-api.';

-- Back to the connecting role: goose records the version in this transaction.
reset role;

-- +goose Down
set local lock_timeout = '5s';
set local role dbcloud_migrator;
drop table dbcloud.api_keys;
drop table dbcloud.memberships;
drop table dbcloud.users;
drop table dbcloud.organizations;
reset role;
