#!/usr/bin/env bash
# Local admin DB helper for the Supabase stack started by `supabase start` (never used against production):
#   admin-db.sh migrate up|down|status|redo|reset   goose on db/migrations, connected as postgres (local only)
#   admin-db.sh roles                               give the service roles LOGIN + random passwords (local only)
#   admin-db.sh env                                 print the DATABASE_URL variables for local services
# Production: roles are created by the Step 1.4 runbook; migrations run as dbcloud_migrator in an in-cell Job.
# Passwords are generated with openssl (CSPRNG, 192 bits) and kept in .local/admin-db.env (git-ignored).
# Requires: goose, psql, openssl. Safe to re-run: `roles` keeps existing passwords.
set -Eeuo pipefail
trap 'echo "admin-db: failed at line $LINENO" >&2' ERR

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
state="${root}/.local/admin-db.env"
# Supabase CLI defaults for the local stack (supabase/config.toml): direct port 54322, pooler 54329.
admin_url="${ADMIN_DB_URL:-postgres://postgres:postgres@127.0.0.1:54322/postgres?sslmode=disable}"

die() { echo "admin-db: $*" >&2; exit 2; }

migrate() {
  [[ "${1:-}" =~ ^(up|down|status|redo|reset)$ ]] || die "usage: admin-db.sh migrate up|down|status|redo|reset"
  goose -dir "${root}/db/migrations" -table dbcloud_goose_version postgres "$admin_url" "$1"
}

roles() {
  mkdir -p "${root}/.local" && chmod 700 "${root}/.local"
  if [[ ! -f "$state" ]]; then
    umask 077
    printf 'DBCLOUD_APP_PASSWORD=%s\nDBCLOUD_WORKER_PASSWORD=%s\nDBCLOUD_MIGRATOR_PASSWORD=%s\n' \
      "$(openssl rand -hex 24)" "$(openssl rand -hex 24)" "$(openssl rand -hex 24)" >"$state"
  fi
  # shellcheck source=/dev/null # generated above, git-ignored
  source "$state"
  # Passwords reach psql as variables on stdin, never as command-line arguments (15-security §4).
  psql -q -v ON_ERROR_STOP=1 "$admin_url" \
    -v app="$DBCLOUD_APP_PASSWORD" -v worker="$DBCLOUD_WORKER_PASSWORD" -v migrator="$DBCLOUD_MIGRATOR_PASSWORD" <<'SQL'
alter role dbcloud_app login password :'app';
alter role dbcloud_worker login password :'worker';
alter role dbcloud_migrator login password :'migrator';
SQL
  echo "roles: dbcloud_app, dbcloud_worker, dbcloud_migrator can log in (passwords in .local/admin-db.env)"
}

env_vars() {
  [[ -f "$state" ]] || die "run 'admin-db.sh roles' first"
  # shellcheck source=/dev/null # generated by roles, git-ignored
  source "$state"
  # control-api uses the transaction pooler (54329, Supavisor tenant "pooler-dev" in the local stack; in
  # production the suffix is the project ref); the worker uses a direct session (54322).
  printf 'APP_DATABASE_URL=postgres://dbcloud_app.pooler-dev:%s@127.0.0.1:54329/postgres?sslmode=disable\n' "$DBCLOUD_APP_PASSWORD"
  printf 'WORKER_DATABASE_URL=postgres://dbcloud_worker:%s@127.0.0.1:54322/postgres?sslmode=disable\n' "$DBCLOUD_WORKER_PASSWORD"
}

main() {
  local cmd="${1:-}"
  shift || true
  case "$cmd" in
    migrate) migrate "$@" ;;
    roles) roles ;;
    env) env_vars ;;
    *) die "usage: admin-db.sh migrate <up|down|status|redo|reset> | roles | env" ;;
  esac
}

main "$@"
