#!/usr/bin/env bash
# Generates db/migrations/00009_river.sql from the pinned River CLI (`river migrate-get`), so River's tables
# are created by goose like every other object (plan/04 Step 0.2) and live in schema dbcloud, owned by
# dbcloud_migrator. Each River version becomes one goose statement block, because River's SQL contains
# function bodies with semicolons. Also records the versions in river_migration so River's own tooling
# agrees with goose. Requires: go (runs the River CLI at the version pinned in go.mod or RIVER_VERSION).
# Rerun after a River upgrade and add the new versions as a new migration; never edit 00009 by hand.
set -Eeuo pipefail
trap 'echo "gen-river-migration: failed at line $LINENO" >&2' ERR

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
river_version="${RIVER_VERSION:-v0.47.0}"
out="${root}/db/migrations/00009_river.sql"

# emit <up|down>: River SQL for all versions, each version wrapped in a goose statement block.
emit() {
  go run "github.com/riverqueue/river/cmd/river@${river_version}" migrate-get --line main --all "--$1" |
    awk '
      /^-- River main migration [0-9]+ \[(up|down)\]/ { if (open) print "-- +goose StatementEnd"; print "-- +goose StatementBegin"; open = 1 }
      { print }
      END { if (open) print "-- +goose StatementEnd" }'
}

main() {
  local up down versions
  up="$(emit up)"
  down="$(emit down)"
  versions="$(grep -cE '^-- River main migration [0-9]+ \[up\]' <<<"$up")"
  {
    echo "-- Code generated by hack/gen-river-migration.sh from River ${river_version}. DO NOT EDIT."
    echo "-- River job-queue tables (${versions} versions) in schema dbcloud, owned by dbcloud_migrator."
    echo
    echo "-- +goose Up"
    echo "set local lock_timeout = '5s';"
    echo "set local role dbcloud_migrator;"
    echo "set local search_path = dbcloud;"
    echo "$up"
    echo "insert into dbcloud.river_migration (line, version) select 'main', v from generate_series(1, ${versions}) as v;"
    echo "-- Back to the connecting role and path: goose records the version in this transaction."
    echo "reset role;"
    echo "reset search_path;"
    echo
    echo "-- +goose Down"
    echo "set local lock_timeout = '5s';"
    echo "set local role dbcloud_migrator;"
    echo "set local search_path = dbcloud;"
    echo "$down"
    echo "reset role;"
    echo "reset search_path;"
  } >"$out"
  echo "wrote ${out#"$root"/} (${versions} River versions)"
}

main "$@"
