// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package queries

import (
	"context"
	"time"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows

insert into dbcloud.idempotency_keys (principal, key, request_hash)
values ($1, $2, $3)
on conflict (principal, key) do nothing
`

type ClaimIdempotencyKeyParams struct {
	Principal   string
	Key         string
	RequestHash []byte
}

// Idempotency-Key records (plan/01 §10.2, 10-engineering §4): the first response to a mutating request is
// stored and replayed for 24 h. Keys are scoped to the authenticated caller (principal); every query filters
// by principal and key, which is the table's primary key. No session state: safe through the transaction pooler.
// Inserts the key as "in progress" (status_code null). 0 rows means the key already exists; the caller then
// reads it with GetIdempotencyKey.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey, arg.Principal, arg.Key, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
update dbcloud.idempotency_keys
set status_code = $1,
    -- Sent as text and cast here: in QueryExecModeExec (transaction pooler) pgx sends []byte as bytea,
    -- which Postgres won't assign to jsonb.
    response = $2::text::jsonb,
    completed_at = now()
where principal = $3
  and key = $4
  and request_hash = $5
  and status_code is null
`

type CompleteIdempotencyKeyParams struct {
	StatusCode  *int16
	Response    string
	Principal   string
	Key         string
	RequestHash []byte
}

// Stores the final response exactly once; a second completion changes nothing.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.StatusCode,
		arg.Response,
		arg.Principal,
		arg.Key,
		arg.RequestHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
select request_hash, status_code, response, created_at
from dbcloud.idempotency_keys
where principal = $1
  and key = $2
`

type GetIdempotencyKeyParams struct {
	Principal string
	Key       string
}

type GetIdempotencyKeyRow struct {
	RequestHash []byte
	StatusCode  *int16
	Response    []byte
	CreatedAt   time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Principal, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const reclaimIdempotencyKey = `-- name: ReclaimIdempotencyKey :execrows
update dbcloud.idempotency_keys
set request_hash = $1,
    status_code = null,
    response = null,
    created_at = now(),
    completed_at = null
where principal = $2
  and key = $3
  and created_at = $4
`

type ReclaimIdempotencyKeyParams struct {
	RequestHash       []byte
	Principal         string
	Key               string
	ObservedCreatedAt time.Time
}

// Takes over a stale in-progress claim or an expired record as a new request. observed_created_at is the
// compare-and-swap token from GetIdempotencyKey: only one of several racing requests wins.
func (q *Queries) ReclaimIdempotencyKey(ctx context.Context, arg ReclaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimIdempotencyKey,
		arg.RequestHash,
		arg.Principal,
		arg.Key,
		arg.ObservedCreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :execrows
delete from dbcloud.idempotency_keys
where principal = $1
  and key = $2
  and request_hash = $3
  and status_code is null
`

type ReleaseIdempotencyKeyParams struct {
	Principal   string
	Key         string
	RequestHash []byte
}

// Drops an in-progress claim after a failure that must not be replayed (5xx, 429, 409, cancelled request),
// so the client can retry with the same key.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.Principal, arg.Key, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
