// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

// Organization API keys. Only the argon2id hash is stored (15-security §3); prefix is the public lookup part. Owner: control-api.
type DbcloudApiKey struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Name       string
	Prefix     string
	Hash       string
	Scopes     []string
	CreatedBy  pgtype.UUID
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
	LastUsedAt *time.Time
}

// Human approval for one exact MCP write (op_hash binds it to the statement); single use. Owner: control-api (approve), mcp-server (consume).
type DbcloudApproval struct {
	ID         uuid.UUID
	GrantID    uuid.UUID
	OpHash     []byte
	TenantID   uuid.UUID
	DatabaseID uuid.UUID
	Actor      uuid.UUID
	Scope      string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	UsedAt     *time.Time
}

// Append-only audit log: services may insert and read, never update or delete; only dbcloud.retention_sweep() removes rows older than 90 days after export (plan/01 §10.2). Owner: every service (insert).
type DbcloudAuditEvent struct {
	ID        uuid.UUID
	At        time.Time
	Actor     string
	ActorType string
	// No foreign key on purpose: audit rows outlive the objects they describe.
	OrgID     pgtype.UUID
	TenantID  pgtype.UUID
	CellID    *string
	Action    string
	Target    string
	RequestID *string
	Details   []byte
}

// Base backups reported by the cell (CNPG Backup objects). Owner: worker.
type DbcloudBackup struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CellID     string
	Kind       string
	StartedAt  time.Time
	FinishedAt *time.Time
	SizeBytes  *int64
	BeginLsn   interface{}
	EndLsn     interface{}
	Status     string
}

// Per-node capacity reported by the cluster-agent; input to placement. Kept 7 days (plan/01 §10.2). Owner: control-api (writes), worker (reads, sweeps).
type DbcloudCapacitySnapshot struct {
	CellID       string
	NodeID       uuid.UUID
	TakenAt      time.Time
	Allocatable  []byte
	Requested    []byte
	LvmFreeBytes int64
	FreePodSlots int32
}

// K3s cells (plan/01 §5). Owner: control-api (registration), worker (capacity).
type DbcloudCell struct {
	ID         string
	Provider   string
	Region     string
	Name       string
	State      string
	K8sVersion *string
	// SHA-256 fingerprint of the cell agent's mTLS client certificate.
	AgentCertFp *string
	// Owner-set spending cap for the capacity controller (plan/03 §10).
	MaxNodes  int16
	Capacity  []byte
	CreatedAt time.Time
}

// Versions of tenant database credentials for create-before-revoke rotation. Never stores the secret (15-security §4). Owner: worker.
type DbcloudCredentialsMetum struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Role      string
	Version   int32
	CreatedAt time.Time
	RevokedAt *time.Time
}

// Desired TenantDatabase spec per tenant and the status the cell agent reports back. Owner: control-api (desired), cluster-agent via control-api (observed).
type DbcloudDatabase struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	CellID   *string
	PgMajor  int16
	// Hour of the week (0-167) of the weekly base backup, staggered per node.
	BackupSlot         *int16
	DesiredGeneration  int64
	DesiredSpec        []byte
	ObservedGeneration int64
	ObservedStatus     []byte
	UpdatedAt          time.Time
}

// Idempotency-Key records: the first response to a mutating request is replayed for 24 h (plan/01 §10.2). status_code null = in progress. Keys are scoped to the authenticated caller, not the org, because POST /v1/orgs has no org yet and a user can act in several orgs. Swept after 24 h by the worker. Owner: control-api.
type DbcloudIdempotencyKey struct {
	// Authenticated caller that sent the key, as kind:id (user:<uuid>, api_key:<uuid>).
	Principal string
	Key       string
	// SHA-256 of method, path, query and body; a reused key with a different request is rejected (422).
	RequestHash []byte
	StatusCode  *int16
	// Replayed response: status headers and base64 body. Responses marked Cache-Control: no-store (one-time secrets) are never stored; only {"no_store": true}.
	Response    []byte
	CreatedAt   time.Time
	CompletedAt *time.Time
}

// GST invoices per organization and billing period; amounts in paise. Retained as a financial record (no sweep). Owner: worker.
type DbcloudInvoice struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Period      pgtype.Range[pgtype.Date]
	AmountPaise int64
	GstPaise    int64
	Currency    string
	RazorpayRef *string
	State       string
	CreatedAt   time.Time
}

// What an MCP client may do for a user in one org: tenants, read or read_write, capabilities. Owner: control-api (consent), mcp-server (checks).
type DbcloudMcpGrant struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ClientID     string
	OrgID        uuid.UUID
	TenantIds    []uuid.UUID
	Mode         string
	Capabilities []string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	RevokedAt    *time.Time
}

// Which user belongs to which organization, with which role. Owner: control-api.
type DbcloudMembership struct {
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

// VMs of each cell; the worker keeps tenant-node A records in sync from this table. Owner: worker.
type DbcloudNode struct {
	ID          uuid.UUID
	CellID      string
	Name        string
	ProviderRef *string
	Role        string
	Vcpu        int16
	MemGb       int16
	DiskGb      int32
	PublicIpv4  *netip.Addr
	State       string
	JoinedAt    *time.Time
}

// MCP OAuth clients: Client ID Metadata Document cache (client_id is the document URL), DCR clients and first-party clients (CLI). Owner: mcp-auth.
type DbcloudOauthClient struct {
	ID        uuid.UUID
	ClientID  string
	Kind      string
	Metadata  []byte
	FetchedAt time.Time
	Blocked   bool
}

// Authorization codes (single use, ≤ 60 s); deleted when redeemed or expired. pkce_challenge is S256 only. Owner: mcp-auth.
type DbcloudOauthCode struct {
	CodeHash      []byte
	ClientID      string
	UserID        uuid.UUID
	GrantID       uuid.UUID
	PkceChallenge string
	Resource      string
	ExpiresAt     time.Time
}

// Rotating refresh tokens; reuse of a rotated token revokes its whole family. Owner: mcp-auth.
type DbcloudOauthRefreshToken struct {
	TokenHash []byte
	ClientID  string
	UserID    uuid.UUID
	GrantID   uuid.UUID
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
}

// Access-token revocation list, pruned once the token would have expired anyway. Owner: mcp-auth.
type DbcloudOauthRevokedToken struct {
	Jti       string
	ExpiresAt time.Time
}

// Every asynchronous change (202 + operation_id); the River job that acts on it commits in the same transaction. Owner: control-api (create), worker (progress).
type DbcloudOperation struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	TenantID          pgtype.UUID
	CellID            *string
	Kind              string
	State             string
	IdempotencyKey    *string
	RequestedBy       pgtype.UUID
	ProviderRequestID *string
	// RFC 9457 problem object when state = failed; never contains secrets.
	Error      []byte
	CreatedAt  time.Time
	FinishedAt *time.Time
}

// Progress log of an operation, shown to the customer. Exported to R2 and swept after 90 days (plan/01 §10.2). Owner: worker.
type DbcloudOperationEvent struct {
	OperationID uuid.UUID
	Seq         int32
	State       string
	Message     string
	At          time.Time
}

// Customer organizations; the tenancy boundary of the control plane. Owner: control-api.
type DbcloudOrganization struct {
	ID   uuid.UUID
	Name string
	Slug string
	// active | past_due | suspended | closed; set by billing jobs from Razorpay state.
	BillingState string
	// Optional GST identification number of the customer, printed on invoices.
	Gstin     *string
	CreatedAt time.Time
}

// Verified Razorpay webhooks, keyed by event id for deduplication (15-security §3). Only the SHA-256 of the payload is kept. Retained as a financial record (no sweep). Owner: control-api (insert), worker (process).
type DbcloudPaymentEvent struct {
	RazorpayEventID string
	ReceivedAt      time.Time
	Kind            string
	PayloadHash     []byte
	ProcessedAt     *time.Time
}

// History of placement decisions (latest row wins). Owner: worker.
type DbcloudPlacement struct {
	TenantID  uuid.UUID
	CellID    string
	NodeID    pgtype.UUID
	DecidedAt time.Time
	Reason    []byte
}

// Plan catalog (plan/03 §4); the only source of tenant resources and Postgres parameters. Rows are managed by migrations and the admin app. Owner: control-api.
type DbcloudPlan struct {
	ID              string
	Name            string
	CpuRequestM     int32
	CpuLimitM       int32
	MemMi           int32
	StorageGb       int32
	StorageClass    string
	Instances       int16
	MaxConnections  int32
	PooledClients   int32
	ArchiveTimeoutS int32
	RetentionDays   int16
	// Postgres parameters rendered by the tenant-operator; never taken from customer input.
	PgParameters []byte
	// Monthly price excluding GST, in paise (₹299 = 29900).
	PricePaise int64
	Active     bool
}

// PITR window per tenant, shown to customers and used by the WAL-archive-age alert. Owner: worker.
type DbcloudRestorePoint struct {
	TenantID                 uuid.UUID
	CellID                   string
	FirstRecoverabilityPoint *time.Time
	LastArchivedWalAt        *time.Time
}

// Public hostnames per tenant and the cell that serves them. Owner: worker.
type DbcloudRoute struct {
	TenantID        uuid.UUID
	HostnamePooled  string
	HostnameDirect  string
	CellID          string
	RouteGeneration int64
	State           string
	CheckedAt       *time.Time
}

// Razorpay subscription per tenant; state mirrors Razorpay's subscription states. Owner: worker (billing jobs).
type DbcloudSubscription struct {
	ID                     uuid.UUID
	OrgID                  uuid.UUID
	TenantID               uuid.UUID
	PlanID                 string
	RazorpaySubscriptionID *string
	State                  string
	CurrentPeriodStart     *time.Time
	CurrentPeriodEnd       *time.Time
	// After a failed renewal the tenant keeps running until this time, then it is suspended (dunning, Step 1.11).
	GraceUntil *time.Time
	CreatedAt  time.Time
}

// One customer database service per row; ref is the opaque public name (t- + base32). Owner: control-api.
type DbcloudTenant struct {
	ID     uuid.UUID
	Ref    string
	OrgID  uuid.UUID
	PlanID string
	Name   string
	// waitlisted | active | suspended | deletion_pending | purged (staged delete, plan/01 §6).
	Lifecycle string
	CreatedAt time.Time
	DeletedAt *time.Time
}

// The only thing that lets a cluster-agent delete a tenant (plan/01 §10.5); purge needs a second approver. Owner: control-api.
type DbcloudTombstone struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	CellID      string
	Generation  int64
	RequestedBy uuid.UUID
	ApprovedBy  pgtype.UUID
	CreatedAt   time.Time
	AppliedAt   *time.Time
}

// Measured usage per tenant and hour, for customer charts and future usage-based add-ons. Exported to R2 and swept after 90 days (plan/01 §10.2). Owner: worker.
type DbcloudUsageHourly struct {
	TenantID       uuid.UUID
	CellID         string
	Hour           time.Time
	CpuMHours      int64
	MemMiHours     int64
	StorageGbHours pgtype.Numeric
	BackupGbHours  pgtype.Numeric
}

// Dashboard users, one row per Supabase Auth user. Owner: control-api.
type DbcloudUser struct {
	ID uuid.UUID
	// Supabase Auth user id (auth.users.id, the JWT sub). No foreign key: auth is owned by Supabase.
	AuthUserID uuid.UUID
	Email      string
	CreatedAt  time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  *time.Time
	CreatedAt    time.Time
	FinalizedAt  *time.Time
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	ID        int64
	CreatedAt time.Time
	Version   int64
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}
